name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: ''
          - goos: linux
            goarch: arm64
            suffix: ''
          - goos: darwin
            goarch: amd64
            suffix: ''
          - goos: darwin
            goarch: arm64
            suffix: ''
          - goos: windows
            goarch: amd64
            suffix: '.exe'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          binary_name="aliwepaystat${{ matrix.suffix }}"
          go build -o "${binary_name}" ./cmd/aliwepaystat/
          zip "aliwepaystat-${{ matrix.goos }}-${{ matrix.goarch }}.zip" "${binary_name}"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: aliwepaystat-${{ matrix.goos }}-${{ matrix.goarch }}.zip
